### PR TITLE
Doc: Fix incorrect use of capture index in selfDoc.

### PR DESCRIPTION
**Pull request by dabiged**
# Summary of changes

The self documentation describing the changes made in #330 are out of date. This PR fixes this issue.

# Description

See Commit changes.

## Type of change

Please delete items that are not relevant.

- Updates documentation to reflect #330 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have confirmed my fix is effective or that my feature works

### CODE REVIEW

**Comment by piste-jp-ibm** [comment]
Did you try the option `--capture-index` on the command `ltfs` ? I believe The description of #330 is not correct.

> - Change --capture-index option in ltfs and ltfsck to have a destination directory

It shall be 

- Change `--capture-index` option in `ltfsck` and `-o capture_index option` in `ltfs` to have a destination directory

---

In the `ltfs` command, options to control behavior of filesystem starts from `-o`. `-o capture_index option` is one of them.

**Comment by piste-jp-ibm** [comment]
Sorry for your confusion.

> It seems from your feedback that it is the man page that is incorrect.

You are correct. The description in [ltfs.sgml](https://github.com/LinearTapeFileSystem/ltfs/blob/master/man/sgml/ltfs.sgml) is not correct and [ltfs.8](https://github.com/LinearTapeFileSystem/ltfs/blob/master/man/ltfs.8) is also incorrect because it is created from [ltfs.sgml](https://github.com/LinearTapeFileSystem/ltfs/blob/master/man/sgml/ltfs.sgml).

**Comment by piste-jp-ibm** [comment]
I rebuild `ltfs.8` and push it on my bench.

The man pages are NOT generated automatically in the build process because the docbook package is required. But it is not provided into the main target OS, RHEL7.

**Comment by piste-jp-ibm** [comment]
@dabiged 

Thank you for your fix !

**Comment by dabiged** [comment]
Thank you @piste-jp-ibm and the whole LTFS for supporting such a fantastic piece of software!

**Pull request merged**
