### PR TITLE
Add NetBSD support

### PR DESCRIPTION
**Pull request by manu0401**
# Summary of changes

This pull request includes following changes or fixes. 

- Add NetBSD support

# Description

This change adds NetBSD support, with two tape drivers:
- scsipi-ibmtape is a port of Linux sg-ibmtape
- ltotape is a port of Linux ltotape from HPE

ltotape is LGPL 2.1 licensed, which as I understand
should be compatible for source distribution with
3-clause BSD licensed LTFS.

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have confirmed my fix is effective or that my feature works

### CODE REVIEW

**Comment by piste-jp-ibm** [comment]
Hi @manu0401,

Thank you for being interested into the LTFS project!

Your PR looks good technically. But I'm very sorry to say, I can't merge it to the repository because of the ltotape backend.

LGPL 2.1 and 3-clause BSD license is not compatible. 3-clause BSD licensed codes can be included into LGPL 2.1 licensed codes easily. But LGPL 2.1 licensed codes cannot be included into 3-clause BSD licensed codes. 

The providers who are providing a commercial S/W based on this repository must open their code if I merge LGPL based code into the repository. For example, IBM provides "IBM Spectrum Archive LE", to support tape library, based on this repository. IBM needs to open their library support code if I merge the PR because there are LGPL 2.1 code and IBM using entire source tree of this repository.

I need to close this PR anyway. Could you remove the ltotape backend and create another PR again?

For ltotape tape backend, I think we need to wait HP changes the license or you can put that in your repository as a 3rd party backend.

**Comment by manu0401** [comment]
Atsushi Abe <notifications@github.com> wrote:

> The providers who are providing a commercial S/W based on this repository
> must open their code if I merge LGPL based code into the repository.

Sorry for reopening that one, but:

I understand this the above is true only if the LGPL code is actually
compiled in. If it is not included, then its license does not apply. 

What about including it disabled by default, with a --enable-ltotape
configure option and documentation warning about the licence? 

ltotape has some merits. I hava a Tandberg LTO6 drive that works with it
but is not supported by ibmtape.

-- 
Emmanuel Dreyfus
http://hcpnet.free.fr/pubz
manu@netbsd.org

**Comment by piste-jp-ibm** [comment]
Hmm, technically. May be you are right.

I will contact to the regal team what is possible (and what is impossible). Please let me have a time to think about  what is the best way from this project and vendors who clones this project entirely.

My idea to use the ltotape backend without any issue is create another project to host the LGPL licensed backends. And the new project use the include file of LTFS and link libraries. How about this?

**Comment by manu0401** [comment]
On Tue, Feb 12, 2019 at 08:16:55PM -0800, Atsushi Abe wrote:
> My idea to use the ltotape backend without any issue is create
> another project to host the LGPL licensed backends.

Thank you for considering it.

Some information about what is done elsewhere: NetBSD has a single
source repository mixing third party code with various licenses,
including various LGPL and GPL flavors. That seems fine, and it
makes sense since this is just a collection of source files. After
all, LGPL does not taint a whole web server content because you
publish one LGPL file on it.

My understanding of LGPL 2.1 is that the only restriction it brings
for source distribution is section 1, which mandates you retain
copyright notice and disclaimer of warranty. Every other section
deals with distribution of object files, And if object file is
generated without using LGPL licensed source, then LGPL license 
on that excluded source files does not apply.

Hence as I understad it, you may distribute LGPL-licensed ltotape
source files in LTFS without any license change to other source
files, but if you want the compiled LTFS to remain BSD licensed,
you have to make sure ltotape is not built in. Someone may want
ltotape features and build a LTFS with ltotape compiled in, and
that person will have to obey LGPL for that LTFS binaries if they
are redistributed.

But (usual disclamer), I am not a lawyer. I hope my input can
help a legal advisor, though.

-- 
Emmanuel Dreyfus
manu@netbsd.org

**Pull request closed without merging**
